#!/bin/sh
# this makes the command to excute on each login
addr="$HOME/test.txt"
# set the backlight porcentage as you like in the variable
light="60"
sed -i -e '$a\# backlight program' '\' $addr 2> /dev/null  # adds the coment
sed -i -e '$a\xbacklight -set '$light'\' $addr 2> /dev/null # adds the command
